apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
spec:
  selector:
    matchLabels:
      app: cart-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: kwon5891/cart-service:latest
          ports:
            - containerPort: 8088